### ISSUE TITLE
please create .env.example file 

### ISSUE THREAD

**Issue by mHarshMittal** [vigneshherao/WanderLust_AirBnB#2]
i am trying to clone the repo but error is comming

Error: Cannot create a client without an access token

**Comment by vigneshherao** [comment]
Environment Variables:

This project requires the following environment variables to be set:

- `cloud_name`
- `api_key`
- `api_secret`
- `map_Token`
- `atlasDb_Url`
- `secret`

Please refer to your server or hosting platform's documentation for instructions on setting up environment variables.


i have also created local file in my repo you can check that!

**Comment by mHarshMittal** [comment]
Thanks
